### ISSUE TITLE
Checker checks itself and fails every time (if installed per project)

### ISSUE THREAD

**Issue by b3nl** [bestit/license-check#2]
$ php vendor/bin/license-check ./    

License (AGPL-3.0-only) of composer package vendorD/package1 is not allowed.

"vendorD/package1" is in a test fixture for unit tests.

Is it checked because BestIt\LicenseCheck\LicenseLoader\ComposerLicenseLoader uses a recursive finder and drills down to this vendor/best-it/license-check/tests/fixtures/composer/fixtures2/composer.lock if it is installed with composer into the project.

**Comment by tim-kellner** [comment]
I have modified the .gitattributes and now the tests folder (and some other unnecessary files) are excluded from the vendor folder.

![Bildschirmfoto 2021-04-06 um 08 19 35](https://user-images.githubusercontent.com/15520044/113667364-00b26080-96b1-11eb-8006-9a1c7a1ba9f5.png)
